services:
  logixmotion:
    build: .
    container_name: logixmotion_web
    restart: unless-stopped
    ports:
      - "8085:3000"
    env_file:
      - .env
    networks:
      - proxy-manager_default
      - default

networks:
  proxy-manager_default:
    external: true